name: "Bot Discord Python 2"
description: "Lance des bots discord en python"
version: "1.1.0"
url: "https://github.com/williamhelle/Bagley-Discord-Personal/",
slug: "discord_bot_no_config"
init: false
map:
  - share
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
startup": "application",
boot": "manual",
host_network": true,
hassio_api": true,
hassio_role": "default",
auth_api": true, 
